### ISSUE TITLE
android手机发现需要重连，但一直链接不上

### ISSUE THREAD

**Issue by kaleai** [benioZhang/miniprogram-bluetoothprinter#8]
不知道是否用过android手机测试过呢，发现蓝牙链接后还是连不上

**Comment by benioZhang** [comment]
> 不知道是否用过android手机测试过呢，发现蓝牙链接后还是连不上

蓝牙连接不上应该找微信吧？

**Comment by kaleai** [comment]
其实就是想问下你这里的android能可以不，因为我这里就一个打印机，所以想问下

**Comment by benioZhang** [comment]
> 其实就是想问下你这里的android能可以不，因为我这里就一个打印机，所以想问下

抱歉，我没使用android设备测试过

**Comment by kaleai** [comment]
多谢啦！
